language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.3"
    - python: "3.4"
    - python: "pypy"
    - python: "pypy3"
    - env: TRAVIS_PIP_UPDATE=false

env:
  global:
    - PY_COLORS=1
  matrix:
    - TRAVIS_PIP_UPDATE=true
    - TRAVIS_PIP_UPDATE=false

cache:
  directories:
    - $HOME/.cache

install:
  - helpers/travis_install.sh

script:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then py.test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m pytest --showlocals; fi
  - flake8 --max-line-length=100 --show-source

after_script:
  - python helpers/greptodo.py
  - python helpers/jssdksyncmon.py
  - python helpers/debug-info.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage combine && codecov; fi
